version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
 
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
      

  appointment-service:
    build: ./appointment-service
    
    ports:
      - "3004:3004"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/appointment-service

  auth-service:
    build: ./auth-service
    
    ports:
      - "3001:3001"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=supersecretkey
      - PORT=3001


  billing-service:
    build: ./billing-service
    ports:
      - "5009:5009"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/billing-service
      - JWT_SECRET=supersecretkey
      - PORT=5009

  consulation-service:
    build: ./consulation-service
    ports:
      - "5006:5006"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/consultation-service
      - PORT=5006
      - JWT_SECRET=supersecretkey

  department-service:
    build: ./department-service
    ports:
      - "3003:3003"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/department-service
      - PORT=3003
      - JWT_SECRET=supersecretkey


  doctor-service:
    build: ./doctor-service
    ports:
      - "3002:3002"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hospital-db
      - PORT=3002
      - JWT_SECRET=supersecretkey


  hospital-admin-schedule-service:
    build: ./hospital-admin-schedule-service
    ports:
      - "3005:3005"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hospital-admin-schedule
      - PORT=3005
      - JWT_SECRET=supersecretkey


  lab-services:
    build: ./lab-services
    ports:
      - "5008:5008"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/lab-service
      - PORT=5008
      - JWT_SECRET=supersecretkey


  nurse-service:
    build: ./nurse-service
    ports:
      - "3007:3007"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nurse-service
      - PORT=3007
      - JWT_SECRET=supersecretkey


  patient-service:
    build: ./patient-service
    ports:
      - "3006:3006"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/patient-service
      - PORT=3006
      - JWT_SECRET=supersecretkey


  frontend-tailwind-css:
    build: ./frontend-tailwind-css
    ports:
      - "5173:5173"
    restart: always
    networks:
      - app-network
    
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge
